apiVersion: v1
kind: Namespace
metadata:
  name: falco
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcosidekick
  namespace: falco
  labels:
    app: falcosidekick
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcosidekick
  template:
    metadata:
      labels:
        app: falcosidekick
    spec:
      containers:
        - name: falcosidekick
          image: falcosecurity/falcosidekick:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2801
              name: http
          env:
            - name: SLACK_WEBHOOKURL
              valueFrom:
                secretKeyRef:
                  name: falcosidekick-secrets
                  key: SLACK_WEBHOOKURL
            - name: DEBUG
              value: "true"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: falcosidekick
  namespace: falco
  labels:
    app: falcosidekick
spec:
  selector:
    app: falcosidekick
  ports:
    - name: http
      port: 2801
      targetPort: 2801
      protocol: TCP
